CREATE TABLE jobs (
    created_date DATE,
    job_title TEXT,
    company TEXT,
    salary TEXT,
    address TEXT,
    link_description TEXT,
    city VARCHAR(50),
    district VARCHAR(50),
    min_salary FLOAT,
    max_salary FLOAT,
    salary_unit VARCHAR(10),
    tag TEXT
);


CREATE TABLE technologies (
	name TEXT
);

CREATE TABLE categories (
    name TEXT,
    group_cat TEXT
);

SELECT 
    t.name AS technology_name,
    COUNT(DISTINCT j.job_title) AS total_jobs
FROM technologies AS t
JOIN jobs AS j 
    ON j.job_title REGEXP CONCAT('\\b', t.name, '\\b')
GROUP BY t.name
HAVING COUNT(DISTINCT j.job_title) > 0
ORDER BY total_jobs DESC;

INSERT INTO categories (name, group_cat) VALUES
('Kinh doanh phần mềm', 'Sales IT Phần mềm'),
('Sales IT Phần mềm khác', 'Sales IT Phần mềm'),
('Kinh doanh Domain/Hosting/Server', 'Sales IT Phần mềm'),
('Thiết kế đồ họa (Graphic Design)', 'Quảng cáo/Sáng tạo'),
('Animation Design', 'Quảng cáo/Sáng tạo'),
('3D Modeler', 'Quảng cáo/Sáng tạo'),
('Ad Operations Manager', 'Quảng cáo/Sáng tạo'),
('Photographer/Video Editor', 'Quảng cáo/Sáng tạo'),
('Backend Developer', 'Software Engineering'),
('Software Engineer', 'Software Engineering'),
('Fullstack Developer', 'Software Engineering'),
('Mobile Developer', 'Software Engineering'),
('Frontend Developer', 'Software Engineering'),
('Blockchain Engineer', 'Software Engineering'),
('IT Helpdesk/IT support', 'IT Infrastructure and Operations'),
('DevOps Engineer', 'IT Infrastructure and Operations'),
('System Administrator', 'IT Infrastructure and Operations'),
('System Engineer', 'IT Infrastructure and Operations'),
('Network Engineer', 'IT Infrastructure and Operations'),
('Kỹ thuật IT', 'IT Infrastructure and Operations'),
('Database Administrator (DBA)', 'IT Infrastructure and Operations'),
('Cloud Engineer', 'IT Infrastructure and Operations'),
('Business Analyst (Phân tích nghiệp vụ)','Product Management'),
('Product Owner/Product Manager','Product Management'),
('Product Analyst/Research','Product Management'),
('Thiết kế đồ họa (Graphic Design)', 'Thiết kế Đồ hoạ/Giao diện/Trải nghiệm'),
('UI/UX Design', 'Thiết kế Đồ hoạ/Giao diện/Trải nghiệm'),
('3D Modeler', 'Thiết kế Đồ hoạ/Giao diện/Trải nghiệm'),
('Illustration', 'Thiết kế Đồ hoạ/Giao diện/Trải nghiệm'),
('Chuyên môn Thiết kế Đồ hoạ/Giao diện/Trải nghiệm khác', 'Thiết kế Đồ hoạ/Giao diện/Trải nghiệm'),
('Chuyên môn Công nghệ thông tin khác', 'Công nghệ thông tin khác'),
('IT Consultant', 'Công nghệ thông tin khác'),
('Quản trị website', 'Công nghệ thông tin khác'),
('Bán hàng kỹ thuật IT', 'Công nghệ thông tin khác'),
('GIS Engineer', 'Công nghệ thông tin khác'),
('Software Tester (Automation & Manual)','Software Testing'),
('QA Engineer', 'Software Testing'),
('Process Quality Assurance (PQA)', 'Software Testing'),
('Automation Tester', 'Software Testing'),
('Game Tester', 'Software Testing'),
('Manual Tester', 'Software Testing'),
('IT Project Manager', 'IT Project Management'),
('Kỹ sư cầu nối BrSE', 'IT Project Management'),
('Scrum Master', 'IT Project Management'),
('IT Comtor', 'IT Project Management'),
('Data Engineer', 'Data Science'),
('Data Analyst', 'Data Science'),
('Data Scientist', 'Data Science');

INSERT INTO technologies (name) VALUES
('Python'),
('Java'),
('JavaScript'),
('TypeScript'),
('C'),
('C++'),
('C#'),
('Go'),
('Rust'),
('PHP'),
('Ruby'),
('Kotlin'),
('Swift'),
('Scala'),
('R'),
('Dart'),
('SQL'),
('MATLAB'),
('Perl'),
('Lua'),
('HTML'),
('CSS'),
('React'),
('Angular'),
('Vue.js'),
('Next.js'),
('Nuxt.js'),
('Svelte'),
('jQuery'),
('Bootstrap'),
('Tailwind CSS'),
('Spring'),
('Spring Boot'),
('Django'),
('Flask'),
('FastAPI'),
('Express.js'),
('NestJS'),
('Laravel'),
('Ruby on Rails'),
('.NET'),
('ASP.NET'),
('Node.js'),
('Android'),
('iOS'),
('Flutter'),
('React Native'),
('SwiftUI'),
('Jetpack Compose'),
('MySQL'),
('PostgreSQL'),
('Oracle'),
('SQL Server'),
('SQLite'),
('MariaDB'),
('MongoDB'),
('Cassandra'),
('DynamoDB'),
('Redis'),
('Neo4j'),
('Couchbase'),
('Hadoop'),
('Spark'),
('Flink'),
('Kafka'),
('Hive'),
('HBase'),
('Airflow'),
('dbt'),
('Trino'),
('Presto'),
('Databricks'),
('Snowflake'),
('BigQuery'),
('Redshift'),
('ClickHouse'),
('StarRocks'),
('Doris'),
('Elasticsearch'),
('Logstash'),
('Kibana'),
('AWS'),
('Azure'),
('GCP'),
('Alibaba Cloud'),
('Oracle Cloud'),
('AWS EC2'),
('AWS S3'),
('AWS Lambda'),
('AWS Glue'),
('AWS Redshift'),
('AWS EMR'),
('Azure VM'),
('Azure Blob'),
('Azure Data Factory'),
('Azure Functions'),
('Google Compute Engine'),
('Google Cloud Storage'),
('Docker'),
('Kubernetes'),
('Jenkins'),
('GitLab CI'),
('GitHub Actions'),
('ArgoCD'),
('Terraform'),
('Ansible'),
('Helm'),
('Prometheus'),
('Grafana'),
('Nginx'),
('Apache'),
('Istio'),
('Git'),
('GitHub'),
('GitLab'),
('Bitbucket'),
('Linux'),
('Ubuntu'),
('Debian'),
('CentOS'),
('Windows'),
('Unix'),
('TensorFlow'),
('PyTorch'),
('Scikit-learn'),
('Keras'),
('XGBoost'),
('LightGBM'),
('Pandas'),
('NumPy'),
('OpenCV'),
('Hugging Face'),
('LangChain'),
('JUnit'),
('PyTest'),
('Selenium'),
('Cypress'),
('Playwright'),
('Postman'),
('REST API'),
('GraphQL'),
('gRPC'),
('Microservices'),
('WebSocket'),
('RabbitMQ'),
('ActiveMQ'),
('OAuth'),
('JWT'),
('Keycloak'),
('OpenSSL'),
('Prometheus'),
('Grafana'),
('Jaeger'),
('OpenTelemetry'),
('VMware'),
('VirtualBox'),
('OpenStack'),
('MinIO'),
('Ceph');
