CREATE TABLE jobs (
    created_date DATE,
    job_title TEXT,
    company TEXT,
    salary TEXT,
    address TEXT,
    link_description TEXT,
    city VARCHAR(50),
    district VARCHAR(50),
    min_salary FLOAT,
    max_salary FLOAT,
    salary_unit VARCHAR(10),
    job_category VARCHAR(50)
);


CREATE TABLE technologies (
	name TEXT
);

SELECT 
    t.name AS technology_name,
    COUNT(DISTINCT j.job_title) AS total_jobs
FROM technologies AS t
JOIN jobs AS j 
    ON j.job_title REGEXP CONCAT('\\b', t.name, '\\b')
GROUP BY t.name
HAVING COUNT(DISTINCT j.job_title) > 0
ORDER BY total_jobs DESC;



INSERT INTO technologies (name) VALUES
('Python'),
('Java'),
('JavaScript'),
('TypeScript'),
('C'),
('C++'),
('C#'),
('Go'),
('Rust'),
('PHP'),
('Ruby'),
('Kotlin'),
('Swift'),
('Scala'),
('R'),
('Dart'),
('SQL'),
('MATLAB'),
('Perl'),
('Lua'),
('HTML'),
('CSS'),
('React'),
('Angular'),
('Vue.js'),
('Next.js'),
('Nuxt.js'),
('Svelte'),
('jQuery'),
('Bootstrap'),
('Tailwind CSS'),
('Spring'),
('Spring Boot'),
('Django'),
('Flask'),
('FastAPI'),
('Express.js'),
('NestJS'),
('Laravel'),
('Ruby on Rails'),
('.NET'),
('ASP.NET'),
('Node.js'),
('Android'),
('iOS'),
('Flutter'),
('React Native'),
('SwiftUI'),
('Jetpack Compose'),
('MySQL'),
('PostgreSQL'),
('Oracle'),
('SQL Server'),
('SQLite'),
('MariaDB'),
('MongoDB'),
('Cassandra'),
('DynamoDB'),
('Redis'),
('Neo4j'),
('Couchbase'),
('Hadoop'),
('Spark'),
('Flink'),
('Kafka'),
('Hive'),
('HBase'),
('Airflow'),
('dbt'),
('Trino'),
('Presto'),
('Databricks'),
('Snowflake'),
('BigQuery'),
('Redshift'),
('ClickHouse'),
('StarRocks'),
('Doris'),
('Elasticsearch'),
('Logstash'),
('Kibana'),
('AWS'),
('Azure'),
('GCP'),
('Alibaba Cloud'),
('Oracle Cloud'),
('AWS EC2'),
('AWS S3'),
('AWS Lambda'),
('AWS Glue'),
('AWS Redshift'),
('AWS EMR'),
('Azure VM'),
('Azure Blob'),
('Azure Data Factory'),
('Azure Functions'),
('Google Compute Engine'),
('Google Cloud Storage'),
('Docker'),
('Kubernetes'),
('Jenkins'),
('GitLab CI'),
('GitHub Actions'),
('ArgoCD'),
('Terraform'),
('Ansible'),
('Helm'),
('Prometheus'),
('Grafana'),
('Nginx'),
('Apache'),
('Istio'),
('Git'),
('GitHub'),
('GitLab'),
('Bitbucket'),
('Linux'),
('Ubuntu'),
('Debian'),
('CentOS'),
('Windows'),
('Unix'),
('TensorFlow'),
('PyTorch'),
('Scikit-learn'),
('Keras'),
('XGBoost'),
('LightGBM'),
('Pandas'),
('NumPy'),
('OpenCV'),
('Hugging Face'),
('LangChain'),
('JUnit'),
('PyTest'),
('Selenium'),
('Cypress'),
('Playwright'),
('Postman'),
('REST API'),
('GraphQL'),
('gRPC'),
('Microservices'),
('WebSocket'),
('RabbitMQ'),
('ActiveMQ'),
('OAuth'),
('JWT'),
('Keycloak'),
('OpenSSL'),
('Prometheus'),
('Grafana'),
('Jaeger'),
('OpenTelemetry'),
('VMware'),
('VirtualBox'),
('OpenStack'),
('MinIO'),
('Ceph');
